[theme]
primaryColor = "#0078D4"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#242424"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = false
